## MLT02: Linear Regression Multiple Variables a.k.a. Multivariate Regression

## Exercise : Hiring 
Objective: Predict recommended salary for candidates below:
* Candidate1: 2-year of experience, 9 test score, 6 interview score
* Candidate2: 12-year experince, 10 test scre, 10 interview score

#### Step 1: Pre-processing Data

In [5]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import word2number

In [6]:
# Define dataframe to use

df = pd.read_csv("hiring.csv")
df


experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [12]:
#clean-up 01: experience
df.experience = df.experience.fillna('zero')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [10]:
#pip3 install word2number
from word2number import w2n
df.experience = df.experience.apply(w2n.word_to_num)


In [11]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [20]:
#Clean-up 02: test_score
df["test_score"] = df["test_score(out of 10)"]

In [25]:
df["iv_score"] = df["interview_score(out of 10)"]
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)  \
0           0                    8.0                           9      50000   
1           0                    8.0                           6      45000   
2           5                    6.0                           7      60000   
3           2                   10.0                          10      65000   
4           7                    9.0                           6      70000   
5           3                    7.0                          10      62000   
6          10                    NaN                           7      72000   
7          11                    7.0                           8      80000   

   test_score  interview_score  iv_score  
0         8.0                9         9  
1         8.0                6         6  
2         6.0                7         7  
3        10.0               10        10  
4         9.0                6         6  
5         7.0               10        10  
6         NaN                7         7  
7         7.0                8         8

In [26]:
#Clean-up 03 : fill-in NaN value in test_score column


In [28]:
import math
median_test_score = math.floor(df.test_score.median())
median_test_score

8

In [30]:
df.test_score = df.test_score.fillna(median_test_score)
df.test_score

0     8.0
1     8.0
2     6.0
3    10.0
4     9.0
5     7.0
6     8.0
7     7.0
Name: test_score, dtype: float64

In [31]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)  \
0           0                    8.0                           9      50000   
1           0                    8.0                           6      45000   
2           5                    6.0                           7      60000   
3           2                   10.0                          10      65000   
4           7                    9.0                           6      70000   
5           3                    7.0                          10      62000   
6          10                    NaN                           7      72000   
7          11                    7.0                           8      80000   

   test_score  interview_score  iv_score  
0         8.0                9         9  
1         8.0                6         6  
2         6.0                7         7  
3        10.0               10        10  
4         9.0                6         6  
5         7.0               10        10  
6         8.0                7         7  
7         7.0                8         8

In [32]:
del df['interview_score']

In [33]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)  \
0           0                    8.0                           9      50000   
1           0                    8.0                           6      45000   
2           5                    6.0                           7      60000   
3           2                   10.0                          10      65000   
4           7                    9.0                           6      70000   
5           3                    7.0                          10      62000   
6          10                    NaN                           7      72000   
7          11                    7.0                           8      80000   

   test_score  iv_score  
0         8.0         9  
1         8.0         6  
2         6.0         7  
3        10.0        10  
4         9.0         6  
5         7.0        10  
6         8.0         7  
7         7.0         8

In [62]:
df.salary

0    50000
1    45000
2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: salary, dtype: int64

#### Step 2: Train Lemear Model

In [65]:
reg = linear_model.LinearRegression()
reg.fit(df[['experience','test_score','iv_score']],df.salary)

LinearRegression()

In [66]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [68]:
reg.intercept_

17737.26346433768

In [69]:
#Candidate 01: recommended salary
reg.predict([['2','9','6']])

C:\Users\Think2019D\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  return f(*args, **kwargs)


array([53205.96797671])

In [70]:
#Candidate 02: recommended salary
reg.predict([['12','10','10']])

C:\Users\Think2019D\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  return f(*args, **kwargs)


array([92002.18340611])

#### Verify calculation
